//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coupon
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public Nullable<int> Discount { get; set; }
        public string Code { get; set; }
        public Product p { get; set; }
    }
}
